### ISSUE TITLE
Errores detectados en la generación de proyecto GeoWE

### ISSUE THREAD

**Issue by jmmluna** [sigdeletras/qgis2geowe#1]
Hola @sigdeletras,
en primer lugar enhorabuena por el script en python que permite generar proyectos de GeoWE desde QGIS. He estado haciendo varias pruebas y he detectado varios detalles que te especifico a continuación:

- Cuando el nombre de las capas tiene tildes en QGIS se genera un error desde el script de python:
_Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\qgis2geowe\qgis2geowe\qgis2geowe.py", line 80, in <module>
    fo.write('{"name": "' + l.name() + '", "content": ')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 31: ordinal not in range(128)_

- Cuando la capa contiene valores de los atributos con tildes no se genera ningún error pero no se carga en GeoWE. Te muestro valores erróneos generados desde el script:
_Tama\\u00f1o y vinculaci\\u00f3n a paisaje_

Un saludo

**Comment by sigdeletras** [comment]
Hola @jmmluna 

Parece que el problema de caracteres se daba en instalaciones de QGIS en Windows. He añadido una recodificación del nombre de la capa. Habría que probar si el error persiste en una capa con atributos con tildes. 
Si puedes hacer una prueba estaría genial.

Dejo el issue abierto hasta que me indiques.
